import asyncio
import os
import sys
import sqlite3
import hashlib
import json
from typing import Any
from pydantic import BaseModel
from google.adk.agents.context import Context
from google.adk.sessions import InMemorySessionService
from google.adk import Runner
from google.adk.runners import RunConfig

import workflow

async def run_mcp_server_and_skills_test():
    print("\n==========================================")
    print("Running Deterministic End-to-End Skills Test")
    print("==========================================")

    # Set environment variable to redirect MCP server to a separate test database
    os.environ["DATABASE_FILE"] = "test_reports.db"

    # 1. Clear test database first
    if os.path.exists("test_reports.db"):
        try:
            os.remove("test_reports.db")
        except:
            pass

    # 2. Setup mock Context using Runner's internal helper
    session_service = InMemorySessionService()
    wf = workflow.create_workflow("gemini-2.5-flash")
    runner = Runner(node=wf, session_service=session_service, auto_create_session=True)
    
    session = await session_service.create_session(
        app_name=runner.app_name, 
        user_id="test_citizen", 
        session_id="test_sess_1"
    )
    
    ic = runner._new_invocation_context(
        session=session,
        run_config=RunConfig(),
        invocation_id="test_inv_1"
    )
    
    ctx = Context(ic)

    raw_report = (
        "Hi, my name is Rahul Sharma.\n"
        "I noticed two large blue chemical drums dumped near the river behind Green Park Apartments, 42 Lake View Road, Bangalore.\n"
        "The water smells terrible and several fish appear to be dead.\n"
        "If you need more information, call me at +91 9876543210 or email me at rahul.sharma@gmail.com."
    )

    print("Step 1: Running Preprocess Node...")
    # Preprocess stores raw report in state
    preprocessed = await workflow.preprocess_raw_report._func(ctx, raw_report)
    assert ctx.state.get("raw_report") == raw_report, "preprocess failed to save raw report"
    print("PASS: Preprocess stored raw report in state.")

    print("\nStep 2: Simulating Privacy Guard Agent output...")
    # Simulated sanitized output (usually generated by PrivacyGuard Agent LLM)
    sanitized_report = (
        "Hi, my name is [REDACTED_NAME].\n"
        "I noticed two large blue chemical drums dumped near the river behind Green Park Apartments, Lake View Area, Bangalore.\n"
        "The water smells terrible and several fish appear to be dead.\n"
        "Phone:\n[REDACTED_CONTACT]\n"
        "Email:\n[REDACTED_CONTACT]"
    )
    print(f"Sanitized report input:\n{sanitized_report}")

    print("\nStep 3: Running Privacy Verification Skill on sanitized report...")
    # This should succeed
    verified_output = await workflow.privacy_verification_skill._func(ctx, sanitized_report)
    assert verified_output == sanitized_report, "verification returned incorrect text"
    assert ctx.state.get("sanitized_report") == sanitized_report, "sanitized report not stored"
    print("PASS: Privacy Verification passed successfully on redacted text.")

    print("\nStep 3b: Testing Privacy Verification Skill leak detection...")
    # Test phone leak
    phone_leak = "Call me at +91 9876543210."
    try:
        await workflow.privacy_verification_skill._func(ctx, phone_leak)
        print("FAIL: Privacy verification did not raise error for phone leak.")
        return False
    except ValueError as e:
        print(f"PASS: Leak check passed. Successfully detected and blocked phone leak: {str(e)}")

    # Test email leak
    email_leak = "My email is test@domain.com."
    try:
        await workflow.privacy_verification_skill._func(ctx, email_leak)
        print("FAIL: Privacy verification did not raise error for email leak.")
        return False
    except ValueError as e:
        print(f"PASS: Leak check passed. Successfully detected and blocked email leak: {str(e)}")

    print("\nStep 4: Simulating Incident Analysis Agent structured output...")
    # Simulated output from IncidentAnalysisAgent LLM matching IncidentAnalysisOutput schema
    llm_output = workflow.IncidentAnalysisOutput(
        hazard_category="Water Pollution",
        general_location="Lake View Area, Bangalore",
        incident_summary="Two chemical drums appear to have contaminated a river, causing foul odor and possible fish deaths.",
        severity_level="High"
    )

    print("\nStep 5: Running Pydantic Validation Layer...")
    incident_report = await workflow.pydantic_validation_layer._func(ctx, llm_output)
    
    # Check generated hash: first 7 characters of SHA-256 hash of "rahul.sharma@gmail.com" (email is matched first)
    expected_identity = "rahul.sharma@gmail.com"
    expected_hash = hashlib.sha256(expected_identity.encode('utf-8')).hexdigest().upper()[:7]
    
    assert incident_report.anonymous_user_hash == expected_hash, f"hash mismatch: expected {expected_hash}, got {incident_report.anonymous_user_hash}"
    assert incident_report.hazard_category == "Water Pollution"
    assert incident_report.severity_level == "High"
    print(f"PASS: Validation Layer success. Computed Hash: {incident_report.anonymous_user_hash}")

    print("\nStep 6: Running Secure Storage Skill (Connects to custom MCP server)...")
    storage_response = await workflow.secure_storage_skill._func(ctx, incident_report)
    
    print(f"MCP Server Response: {storage_response}")
    assert storage_response.get("status") == "Success", "MCP storage reported failure"
    assert storage_response.get("incident_id") == "INC-1001", f"Expected INC-1001, got {storage_response.get('incident_id')}"
    print("PASS: Secure Storage Skill passed and logged to SQLite via MCP Server.")

    print("\nStep 7: Directly verifying database integrity...")
    conn = sqlite3.connect("test_reports.db")
    cursor = conn.cursor()
    cursor.execute("SELECT id, user_hash, category, location, summary, severity FROM reports")
    rows = cursor.fetchall()
    conn.close()

    assert len(rows) == 1, "Database should have exactly 1 row"
    row = rows[0]
    assert row[1] == expected_hash, "DB hash mismatch"
    assert row[2] == "Water Pollution", "DB category mismatch"
    assert row[5] == "High", "DB severity mismatch"
    print("PASS: SQLite database integrity check passed: No PII stored, only sanitized details present.")

    # Clean up test database file
    try:
        os.remove("test_reports.db")
    except:
        pass
    return True

if __name__ == "__main__":
    success = asyncio.run(run_mcp_server_and_skills_test())
    sys.exit(0 if success else 1)
